# Generated by Django 5.0.1 on 2024-01-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_coursesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="enrolment_cap",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
