# Generated by Django 5.0.1 on 2024-01-25 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_course_enrolment_cap"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursesubject",
            old_name="subject",
            new_name="name",
        ),
    ]
