# Generated by Django 5.0.1 on 2024-01-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_rename_subject_coursesubject_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesubject",
            name="credit",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
