# Generated by Django 5.0.1 on 2024-01-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_coursesubject_credit"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolment",
            name="priority",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrolment",
            name="tokens",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="enrolment",
            unique_together={("student", "priority")},
        ),
        migrations.DeleteModel(
            name="Pick",
        ),
    ]
