# Generated by Django 4.2.7 on 2023-11-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseannouncement",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="course.course"
            ),
        ),
    ]
