@startuml packages
set namespaceSeparator none
package "course" as course #77AADD {
}
package "course.admin" as course.admin #77AADD {
}
package "course.apps" as course.apps #77AADD {
}
package "course.models" as course.models #77AADD {
}
package "course.tests" as course.tests #77AADD {
}
package "course.views" as course.views #77AADD {
}
course.views --> course.models
@enduml
